In [110]:
import numpy as np
import pandas as pd
import os

In [111]:
os.chdir('/Users/suparvitp/Programming/internshipPlacementSelectionSystem')

In [112]:
input_file = './RxCU85DrugStore.csv'
df = pd.read_csv(input_file)
df

,Unnamed: 0,Unnamed: 1,ผลัดที่ 1 (4 มิ.ย. - 1 ก.ค. 69),Unnamed: 3,ผลัดที่ 2 (2 - 31 ก.ค. 69),Unnamed: 5,ผลัดที่ 3 (เสาร์ อาทิตย์ 1 ส.ค. - 4 ต.ค. 69),Unnamed: 7,ข้อมูลติดต่อ,หมายเหตุ,...,เวลาปฏิบัติการของเภสัชกร,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,ประเภทแหล่งฝึก,ศูนย์ / สาขา,ระบุเพศ,จำนวน,ระบุเพศ,จำนวน,,จำนวน,ที่อยู่,ข้อมูลเพิ่มเติม,...,เวลาเริ่มงาน,เวลาเลิกงาน,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ศบส. กองเภสัชกรรม,1 สะพานมอญ,ไม่ระบุเพศ,1,ไม่รับ,NaN,ไม่รับ,NaN,เลขที่ 3-5 ถ. เจริญกรุง วังบูรพาภิรมย์ พระนคร ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ศบส. กองเภสัชกรรม,2 วัดมักกะสัน,ช เท่านั้น,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,ตั้งอยู่ภายในวัดดิสหงษาราม (วัดมักกะสัน) เลขท...,ศูนย์อยู่ในวัดและนิสิตต้องออกไปทานอาหารข้างนอก,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ศบส. กองเภสัชกรรม,6 สโมสรวัฒนธรรมหญิง,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,เลขที่ 426 ถนนพิษณุโลก แขวงสี่แยกมหานาค เขต...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ศบส. กองเภสัชกรรม,14 แก้ว สีบุญเรือง,ไม่ระบุเพศ,1,ไม่ระบุเพศ,1,ไม่รับ,NaN,21 ซอยจันทน์ 42 (ติดวัดลุ่มเจริญศรัทธา) ถนน...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
df = df.dropna(axis=0, how='all')
df = df.dropna(axis=1, how='all')
df

,Unnamed: 0,Unnamed: 1,ผลัดที่ 1 (4 มิ.ย. - 1 ก.ค. 69),Unnamed: 3,ผลัดที่ 2 (2 - 31 ก.ค. 69),Unnamed: 5,ผลัดที่ 3 (เสาร์ อาทิตย์ 1 ส.ค. - 4 ต.ค. 69),Unnamed: 7,ข้อมูลติดต่อ,หมายเหตุ,Unnamed: 10,เวลาเปิด-ปิดสาขา,Unnamed: 12,เวลาปฏิบัติการของเภสัชกร,Unnamed: 14,Unnamed: 15
0,ประเภทแหล่งฝึก,ศูนย์ / สาขา,ระบุเพศ,จำนวน,ระบุเพศ,จำนวน,,จำนวน,ที่อยู่,ข้อมูลเพิ่มเติม,ข้อเสนอแนะ,เวลาเปิด,เวลาปิด,เวลาเริ่มงาน,เวลาเลิกงาน,NaN
1,ศบส. กองเภสัชกรรม,1 สะพานมอญ,ไม่ระบุเพศ,1,ไม่รับ,NaN,ไม่รับ,NaN,เลขที่ 3-5 ถ. เจริญกรุง วังบูรพาภิรมย์ พระนคร ...,NaN,ขอรับนิสิตฝึกงานที่มีความตั้งใจและรับผิดชอบในก...,NaN,NaN,NaN,NaN,NaN
2,ศบส. กองเภสัชกรรม,2 วัดมักกะสัน,ช เท่านั้น,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,ตั้งอยู่ภายในวัดดิสหงษาราม (วัดมักกะสัน) เลขท...,ศูนย์อยู่ในวัดและนิสิตต้องออกไปทานอาหารข้างนอก,ต้องเตรียมความรู้และทักษะพื้นฐาน เป้าหมายในอนา...,NaN,NaN,NaN,NaN,NaN
3,ศบส. กองเภสัชกรรม,6 สโมสรวัฒนธรรมหญิง,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,เลขที่ 426 ถนนพิษณุโลก แขวงสี่แยกมหานาค เขต...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ศบส. กองเภสัชกรรม,14 แก้ว สีบุญเรือง,ไม่ระบุเพศ,1,ไม่ระบุเพศ,1,ไม่รับ,NaN,21 ซอยจันทน์ 42 (ติดวัดลุ่มเจริญศรัทธา) ถนน...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,ร้านยา Fascino,หัวหิน มาร์เก็ต วิลเลจ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,Market Village 234/1(ห้อง A128/1) ถ.เพชรเกษม ต...,NaN,NaN,NaN,NaN,NaN,NaN,10.30-21.00
230,ร้านยา Fascino,อมตะ ชลบุรี,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,8/169-170 หมู่ที่4 ตำบลดอนหัวฬ่อ อำเภอเมืองชล...,NaN,NaN,NaN,NaN,NaN,NaN,9.00-21.00
231,ร้านยา Fascino,อรุณอมรินทร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,979 ถ.อรุณอัมรินทร์ แขวงศิริราช เขตบางกอกน้อย ...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-20.00
232,ร้านยา Fascino,อุบลสแควร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,เลขที่ 941/7 ห้อง A4/FCINO ถนนชยางกูร ตำบลในเ...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-21.00
233,ร้านยา Fascino,Caltex นาจอมเทียน-แยกบ้านอำเภอ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,247/20 หมู่ 9 ตำบลนาจอมเทียน อำเภอสัตหีบ จ.ช...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-21.00

In [114]:
df = df.rename(columns={
   'Unnamed: 0':'company',
   'Unnamed: 1':'branch',
   'ที่อยู่':'address',
   'ผลัดที่ 1 (4 มิ.ย. - 1 ก.ค. 69)':'sex_require1',
   'Unnamed: 3':'seat1',
   'ผลัดที่ 2 (2 - 31 ก.ค. 69)':'sex_require2',
   'Unnamed: 5':'seat2',
   'ผลัดที่ 3 (เสาร์ อาทิตย์ 1 ส.ค. - 4 ต.ค. 69)':'sex_require3',
   'Unnamed: 7':'seat3'
})

In [115]:
df = df.drop(index=0, errors='ignore')
df

,company,branch,sex_require1,seat1,sex_require2,seat2,sex_require3,seat3,ข้อมูลติดต่อ,หมายเหตุ,Unnamed: 10,เวลาเปิด-ปิดสาขา,Unnamed: 12,เวลาปฏิบัติการของเภสัชกร,Unnamed: 14,Unnamed: 15
1,ศบส. กองเภสัชกรรม,1 สะพานมอญ,ไม่ระบุเพศ,1,ไม่รับ,NaN,ไม่รับ,NaN,เลขที่ 3-5 ถ. เจริญกรุง วังบูรพาภิรมย์ พระนคร ...,NaN,ขอรับนิสิตฝึกงานที่มีความตั้งใจและรับผิดชอบในก...,NaN,NaN,NaN,NaN,NaN
2,ศบส. กองเภสัชกรรม,2 วัดมักกะสัน,ช เท่านั้น,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,ตั้งอยู่ภายในวัดดิสหงษาราม (วัดมักกะสัน) เลขท...,ศูนย์อยู่ในวัดและนิสิตต้องออกไปทานอาหารข้างนอก,ต้องเตรียมความรู้และทักษะพื้นฐาน เป้าหมายในอนา...,NaN,NaN,NaN,NaN,NaN
3,ศบส. กองเภสัชกรรม,6 สโมสรวัฒนธรรมหญิง,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,เลขที่ 426 ถนนพิษณุโลก แขวงสี่แยกมหานาค เขต...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ศบส. กองเภสัชกรรม,14 แก้ว สีบุญเรือง,ไม่ระบุเพศ,1,ไม่ระบุเพศ,1,ไม่รับ,NaN,21 ซอยจันทน์ 42 (ติดวัดลุ่มเจริญศรัทธา) ถนน...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ศบส. กองเภสัชกรรม,18 มงคล-วอน วังตาล,ไม่ระบุเพศ,2,ไม่รับ,NaN,ไม่รับ,NaN,เลขที่ 863/2 ซ.วัดไผ่เงิน ถ.จันทร์ แขวงบางโคล่...,สำรวจเส้นทางล่วงหน้าก่อนวันฝึกงาน ทบทวนความรู้...,ปฏิบัติตามแนวทางการฝึกงาน ในคู่มือฝึกปฏิบัติงา...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,ร้านยา Fascino,หัวหิน มาร์เก็ต วิลเลจ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,Market Village 234/1(ห้อง A128/1) ถ.เพชรเกษม ต...,NaN,NaN,NaN,NaN,NaN,NaN,10.30-21.00
230,ร้านยา Fascino,อมตะ ชลบุรี,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,8/169-170 หมู่ที่4 ตำบลดอนหัวฬ่อ อำเภอเมืองชล...,NaN,NaN,NaN,NaN,NaN,NaN,9.00-21.00
231,ร้านยา Fascino,อรุณอมรินทร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,979 ถ.อรุณอัมรินทร์ แขวงศิริราช เขตบางกอกน้อย ...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-20.00
232,ร้านยา Fascino,อุบลสแควร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,เลขที่ 941/7 ห้อง A4/FCINO ถนนชยางกูร ตำบลในเ...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-21.00
233,ร้านยา Fascino,Caltex นาจอมเทียน-แยกบ้านอำเภอ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,247/20 หมู่ 9 ตำบลนาจอมเทียน อำเภอสัตหีบ จ.ช...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-21.00

In [116]:
company_prefix = {
    'ศบส. กองเภสัชกรรม': 'CEN',
    'ร้านยากรุงเทพ': 'BKK',
    'ร้านยา Boots': 'BTS',
    'โรงพยาบาลตำรวจ': 'HPT',
    'จามฯ 9': 'CHA',
    'ร้านยา Pure': 'PUR',
    'ร้านยา Fascino': 'FCN',
}

# รันเลขจาก 1 ไป n
df['company'] = df['company'].ffill()

counters = {prefix: 1 for prefix in company_prefix.values()}
df['code'] = None

for idx in df.index:
    company = df.loc[idx, 'company']
    if company in company_prefix:
        prefix = company_prefix[company]
        df.loc[idx, 'code'] = f'{prefix}{counters[prefix]:02d}'
        counters[prefix] += 1

df

,company,branch,sex_require1,seat1,sex_require2,seat2,sex_require3,seat3,ข้อมูลติดต่อ,หมายเหตุ,Unnamed: 10,เวลาเปิด-ปิดสาขา,Unnamed: 12,เวลาปฏิบัติการของเภสัชกร,Unnamed: 14,Unnamed: 15,code
1,ศบส. กองเภสัชกรรม,1 สะพานมอญ,ไม่ระบุเพศ,1,ไม่รับ,NaN,ไม่รับ,NaN,เลขที่ 3-5 ถ. เจริญกรุง วังบูรพาภิรมย์ พระนคร ...,NaN,ขอรับนิสิตฝึกงานที่มีความตั้งใจและรับผิดชอบในก...,NaN,NaN,NaN,NaN,NaN,CEN01
2,ศบส. กองเภสัชกรรม,2 วัดมักกะสัน,ช เท่านั้น,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,ตั้งอยู่ภายในวัดดิสหงษาราม (วัดมักกะสัน) เลขท...,ศูนย์อยู่ในวัดและนิสิตต้องออกไปทานอาหารข้างนอก,ต้องเตรียมความรู้และทักษะพื้นฐาน เป้าหมายในอนา...,NaN,NaN,NaN,NaN,NaN,CEN02
3,ศบส. กองเภสัชกรรม,6 สโมสรวัฒนธรรมหญิง,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่รับ,NaN,เลขที่ 426 ถนนพิษณุโลก แขวงสี่แยกมหานาค เขต...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CEN03
4,ศบส. กองเภสัชกรรม,14 แก้ว สีบุญเรือง,ไม่ระบุเพศ,1,ไม่ระบุเพศ,1,ไม่รับ,NaN,21 ซอยจันทน์ 42 (ติดวัดลุ่มเจริญศรัทธา) ถนน...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CEN04
5,ศบส. กองเภสัชกรรม,18 มงคล-วอน วังตาล,ไม่ระบุเพศ,2,ไม่รับ,NaN,ไม่รับ,NaN,เลขที่ 863/2 ซ.วัดไผ่เงิน ถ.จันทร์ แขวงบางโคล่...,สำรวจเส้นทางล่วงหน้าก่อนวันฝึกงาน ทบทวนความรู้...,ปฏิบัติตามแนวทางการฝึกงาน ในคู่มือฝึกปฏิบัติงา...,NaN,NaN,NaN,NaN,NaN,CEN05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,ร้านยา Fascino,หัวหิน มาร์เก็ต วิลเลจ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,Market Village 234/1(ห้อง A128/1) ถ.เพชรเกษม ต...,NaN,NaN,NaN,NaN,NaN,NaN,10.30-21.00,FCN94
230,ร้านยา Fascino,อมตะ ชลบุรี,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,8/169-170 หมู่ที่4 ตำบลดอนหัวฬ่อ อำเภอเมืองชล...,NaN,NaN,NaN,NaN,NaN,NaN,9.00-21.00,FCN95
231,ร้านยา Fascino,อรุณอมรินทร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,979 ถ.อรุณอัมรินทร์ แขวงศิริราช เขตบางกอกน้อย ...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-20.00,FCN96
232,ร้านยา Fascino,อุบลสแควร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,เลขที่ 941/7 ห้อง A4/FCINO ถนนชยางกูร ตำบลในเ...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-21.00,FCN97
233,ร้านยา Fascino,Caltex นาจอมเทียน-แยกบ้านอำเภอ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,247/20 หมู่ 9 ตำบลนาจอมเทียน อำเภอสัตหีบ จ.ช...,NaN,NaN,NaN,NaN,NaN,NaN,8.00-21.00,FCN98

In [117]:
df = df[['code','branch','sex_require1','seat1','sex_require2','seat2','sex_require3','seat3']]
df

,code,branch,sex_require1,seat1,sex_require2,seat2,sex_require3,seat3
1,CEN01,1 สะพานมอญ,ไม่ระบุเพศ,1,ไม่รับ,NaN,ไม่รับ,NaN
2,CEN02,2 วัดมักกะสัน,ช เท่านั้น,2,ไม่ระบุเพศ,2,ไม่รับ,NaN
3,CEN03,6 สโมสรวัฒนธรรมหญิง,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่รับ,NaN
4,CEN04,14 แก้ว สีบุญเรือง,ไม่ระบุเพศ,1,ไม่ระบุเพศ,1,ไม่รับ,NaN
5,CEN05,18 มงคล-วอน วังตาล,ไม่ระบุเพศ,2,ไม่รับ,NaN,ไม่รับ,NaN
...,...,...,...,...,...,...,...,...
229,FCN94,หัวหิน มาร์เก็ต วิลเลจ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2
230,FCN95,อมตะ ชลบุรี,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2
231,FCN96,อรุณอมรินทร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2
232,FCN97,อุบลสแควร์,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2
233,FCN98,Caltex นาจอมเทียน-แยกบ้านอำเภอ,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2,ไม่ระบุเพศ,2

In [118]:
for i in range(1,4):
    df.loc[:, f'seat{i}'] = df[f'seat{i}'].fillna(0)

In [119]:
sex_map = {
    'ไม่ระบุเพศ': 'Both',
    'ช เท่านั้น': 'Male',
    'ช': 'Male',
    'ญ เท่านั้น': 'Female',
    'ญ': 'Female',
    'ไม่รับ': None
}

for j in range(1, 4):
    col = f'sex_require{j}'
    df[col] = df[col].apply(lambda x: sex_map.get(str(x).strip(), None) if pd.notna(x) and str(x).strip() != '' else None)

df

/var/folders/qf/ks5pl7h12n145pj927slrc1w0000gn/T/ipykernel_27629/4020868743.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].apply(lambda x: sex_map.get(str(x).strip(), None) if pd.notna(x) and str(x).strip() != '' else None)

,code,branch,sex_require1,seat1,sex_require2,seat2,sex_require3,seat3
1,CEN01,1 สะพานมอญ,Both,1,None,0,None,0
2,CEN02,2 วัดมักกะสัน,Male,2,Both,2,None,0
3,CEN03,6 สโมสรวัฒนธรรมหญิง,Both,2,Both,2,None,0
4,CEN04,14 แก้ว สีบุญเรือง,Both,1,Both,1,None,0
5,CEN05,18 มงคล-วอน วังตาล,Both,2,None,0,None,0
...,...,...,...,...,...,...,...,...
229,FCN94,หัวหิน มาร์เก็ต วิลเลจ,Both,2,Both,2,Both,2
230,FCN95,อมตะ ชลบุรี,Both,2,Both,2,Both,2
231,FCN96,อรุณอมรินทร์,Both,2,Both,2,Both,2
232,FCN97,อุบลสแควร์,Both,2,Both,2,Both,2
233,FCN98,Caltex นาจอมเทียน-แยกบ้านอำเภอ,Both,2,Both,2,Both,2

In [120]:
df

,code,branch,sex_require1,seat1,sex_require2,seat2,sex_require3,seat3
1,CEN01,1 สะพานมอญ,Both,1,None,0,None,0
2,CEN02,2 วัดมักกะสัน,Male,2,Both,2,None,0
3,CEN03,6 สโมสรวัฒนธรรมหญิง,Both,2,Both,2,None,0
4,CEN04,14 แก้ว สีบุญเรือง,Both,1,Both,1,None,0
5,CEN05,18 มงคล-วอน วังตาล,Both,2,None,0,None,0
...,...,...,...,...,...,...,...,...
229,FCN94,หัวหิน มาร์เก็ต วิลเลจ,Both,2,Both,2,Both,2
230,FCN95,อมตะ ชลบุรี,Both,2,Both,2,Both,2
231,FCN96,อรุณอมรินทร์,Both,2,Both,2,Both,2
232,FCN97,อุบลสแควร์,Both,2,Both,2,Both,2
233,FCN98,Caltex นาจอมเทียน-แยกบ้านอำเภอ,Both,2,Both,2,Both,2

In [121]:
df.to_csv('./cleanRxCU85DrugStore.csv', index=False)

In [122]:
sex_cols = ['sex_require1', 'sex_require2', 'sex_require3']

pur_sex_mask = df['code'].astype(str).str.startswith('PUR', na=False)
valid_sex_mask = df[sex_cols].apply(
    lambda col: col.isna() | (col == 'Male')
).all(axis=1)

pur_sex_discrimination = df[pur_sex_mask & valid_sex_mask].copy()
pur_sex_discrimination

,code,branch,sex_require1,seat1,sex_require2,seat2,sex_require3,seat3
93,PUR01,เพรียว สำโรง,None,0,None,0,None,0
100,PUR08,เพรียว ขอนแก่น,Male,2,Male,2,Male,2
101,PUR09,เพรียว อุบลราชธานี,None,0,Male,2,Male,2
102,PUR10,เพรียว พิบูลมังสาหาร,None,0,Male,2,Male,2
103,PUR11,เพรียว ศรีสะเกษ,Male,2,Male,2,Male,2
104,PUR12,เพรียว สุรินทร์,None,0,Male,2,Male,2
105,PUR13,เพรียว บุรีรัมย์,None,0,Male,2,Male,2
106,PUR14,เพรียว เลย,None,0,Male,2,Male,2
107,PUR15,เพรียว สกลนคร,None,0,Male,2,Male,2
108,PUR16,เพรียว ร้อยเอ็ด,None,0,Male,2,Male,2
109,PUR17,เพรียว อำนาจเจริญ,None,0,Male,2,Male,2
110,PUR18,เพรียว กาฬสินธ์,None,0,Male,2,Male,2
111,PUR19,เพรียว เอกมัย,None,0,Male,2,Male,2
112,PUR20,เพรียว นครพนม,None,0,Male,2,Male,2
113,PUR21,เพรียว อ่อนนุช,None,0,Male,2,Male,2
114,PUR22,เพรียว กระนวน,None,0,Male,2,Male,2
115,PUR23,เพรียว หัวหมาก,Male,2,Male,2,Male,2
121,PUR29,เพรียว พัทยา 3,None,0,None,0,None,0
122,PUR30,เพรียว ลาดพร้าว 2,None,0,None,0,Male,1
123,PUR31,เพรียว ภูเก็ต,None,0,None,0,None,0
124,PUR32,เพรียว สตูล,None,0,None,0,None,0
125,PUR33,เพรียว สมุย,None,0,None,0,None,0
126,PUR34,เพรียว นครศรีธรรมราช2,None,0,None,0,None,0
128,PUR36,เพรียว พระราม 2,None,0,None,0,None,0
129,PUR37,เพรียว ราชบุรี,None,0,None,0,None,0
131,PUR39,เพรียว บางปะกอก,Male,1,None,0,None,0
133,PUR41,เพรียว เพชรเกษม 2,None,0,None,0,None,0
135,PUR43,เพรียว เพชรเกษม 1,Male,1,None,0,None,0